class LogEventDescription:
    def __init__(self):
        self._event_descriptions = {}
        self.load_event_descriptions()

    def load_event_descriptions(self):
        self._event_descriptions = {
            0: "Allarme",
            1: "Ripristino Allarme",
            2: "Bypass",
            3: "Ripristino Bypass", 
            4: "Tamper",
            5: "Ripristino Tamper",
            6: "Problema",
            7: "Ripristino Problema",
            8: "Batteria TX Scarica",
            9: "Ripristino TX Batteria Scarica",
            10: "Zona Persa",
            11: "Rispristino Zona Persa",
            12: "Inizio Tempo di Attraversamento",
            13: "Supervisione Sprinkler",
            14: "Ripristinata Supervisione Sprinkler",
            15: "Zona Inattiva",
            16: "Ripristino Zona Inattiva",
            17: "Evento di Espansione Speciale",
            18: "Coercizione",
            19: "Attivazione Manuale",
            20: "Ausiliario 2 Panico",
            21: "Silenzioso Panico/ B - Allarme",
            22: "Panico",
            23: "Tamper Tastiera",
            24: "Box di Controllo Tamper",
            25: "Ripristino Box di Controllo Tamper",
            26: "Alimentazione Primaria",
            27: "Ripristino Alimentazione Primaria",
            28: "Batteria Scarica",
            29: "Ripristino Batteria Scarica",
            30: "Sovracorrente",
            31: "Ripristino Sovracorrente",
            32: "Tamper Sirena",
            33: "Ripristino Tamper Sirena",
            34: "Guasto Telefonico",
            35: "Ripristino Guasto Telefonico",
            36: "Problemi all'Expander",
            37: "Ripristino Problemi all'Expander",
            38: "Errore di Comunicazione",
            39: "Log Eventi Pieno",
            40: "Disinserimento",
            41: "Inserimento",
            42: "Errore di Uscita",
            43: "Inserimento Recente",
            44: "Auto Test",
            45: "Entrata in Programmazione",
            46: "Termine Programmazione",
            47: "Inizio Download",
            48: "Download Terminato",
            49: "Annulla",
            50: "Guasto Terra",
            51: "Ripristino Guasto Terra",
            52: "Test Manuale",
            53: "Inserimento con Zone Bypassate",
            54: "Inizia l'Ascolto in",
            55: "Tecnico in Programmazione",
            56: "Tecnico fuori Programmazione",
            57: "Controlo Alimentazione",
            58: "Anticipo di Apertura",
            59: "Ritardo di Chiusura",
            60: "Blocco RF",
            61: "Ripristino Blocco RF",
            62: "Zona Clean-Me",
            63: "Ripristino Zona Clean-Me",
            64: "Verificata Intrusione",
            65: "Ripristiono Verificata Intrusione",
            66: "Verificato Incendio",
            67: "Ripristino Verificato Incendio",
            68: "Disinserimento Dopo l'Allarme"
        }

    def get_description(self, event_code):
        return self._event_descriptions.get(event_code, f"Unknown Event {event_code}")
